-- Create Blog Posts Table
CREATE TABLE IF NOT EXISTS "public"."Blog_Posts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "title" text NOT NULL,
    "excerpt" text,
    "content" text,
    "image_url" text,
    "published_at" date DEFAULT CURRENT_DATE,
    "slug" text UNIQUE
);

-- Create Services Table
CREATE TABLE IF NOT EXISTS "public"."Services" (
    "id" text PRIMARY KEY, -- using text id like 'transfer', 'tour' to match existing frontend logic
    "created_at" timestamp with time zone DEFAULT now(),
    "title" text NOT NULL,
    "description" text,
    "icon_name" text, -- store icon name as string (e.g. 'car', 'map')
    "image_url" text
);

-- Enable RLS
ALTER TABLE "public"."Blog_Posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Services" ENABLE ROW LEVEL SECURITY;

-- Policies (Public Read, Admin Write)
CREATE POLICY "Enable read access for all users" ON "public"."Blog_Posts" FOR SELECT USING (true);
CREATE POLICY "Enable write access for authenticated users only" ON "public"."Blog_Posts" FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON "public"."Services" FOR SELECT USING (true);
CREATE POLICY "Enable write access for authenticated users only" ON "public"."Services" FOR ALL USING (auth.role() = 'authenticated');

-- Seed Data (from lib/data.ts)
INSERT INTO "public"."Blog_Posts" (title, excerpt, published_at, image_url, slug)
VALUES
('İstanbul''un Gizli Hazineleri', 'Turist rehberlerinde bulamayacağınız, şehrin en büyüleyici tarihi sokakları ve lezzet durakları.', '2025-12-12', 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80', 'istanbul-gizli-hazineleri'),
('Mükemmel Bir Spa Deneyimi İçin İpuçları', 'Vücudunuzu ve ruhunuzu dinlendirmek için spa ritüellerinin inceliklerini keşfedin.', '2025-11-05', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80', 'mukemmel-spa-deneyimi'),
('Bodrum''da Gün Batımı Rotaları', 'Ege''nin en güzel gün batımını izleyebileceğiniz en romantik ve huzurlu noktalar.', '2025-10-20', 'https://images.unsplash.com/photo-1580242279262-d9c9fb7d2062?auto=format&fit=crop&w=800&q=80', 'bodrum-gun-batimi')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO "public"."Services" (id, title, description, icon_name)
VALUES
('transfer', 'VIP Havaalanı Transferi', 'Sizi havaalanında karşılıyor, lüks araçlarımızla otelinize konforlu bir şekilde ulaştırıyoruz.', 'car'),
('tour', 'Özel Şehir Turları', 'Profesyonel rehberler eşliğinde İstanbul''un ve Bodrum''un tarihi güzelliklerini keşfedin.', 'map'),
('concierge', 'Kişisel Asistan (Concierge)', 'Restoran rezervasyonlarından etkinlik biletlerine kadar her türlü isteğiniz için 7/24 hizmetinizdeyiz.', 'bell')
ON CONFLICT (id) DO NOTHING;
