-- Chat Sessions Table
CREATE TABLE IF NOT EXISTS "public"."Chat_Sessions" (
    "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "customer_name" text DEFAULT 'Ziyaretçi',
    "status" text DEFAULT 'active', -- 'active', 'closed'
    "last_message_at" timestamp with time zone DEFAULT now()
);

-- Chat Messages Table
CREATE TABLE IF NOT EXISTS "public"."Chat_Messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "session_id" uuid REFERENCES "public"."Chat_Sessions"("id") ON DELETE CASCADE,
    "sender" text NOT NULL, -- 'user' or 'admin'
    "message" text NOT NULL,
    "is_read" boolean DEFAULT false
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."Chat_Sessions";
ALTER PUBLICATION supabase_realtime ADD TABLE "public"."Chat_Messages";

-- RLS (Basitleştirilmiş: Herkes yazabilir, sadece Admin okuyabilir/yanıtlayabilir)
ALTER TABLE "public"."Chat_Sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Chat_Messages" ENABLE ROW LEVEL SECURITY;

-- Public Policies (Ziyaretçiler için)
-- Ziyaretçilerin kendi oturumlarını oluşturabilmesi ve mesaj atabilmesi lazım.
-- Güvenlik Notu: Anonim erişimde session_id'yi bilen herkes o oturuma yazabilir.
-- Prodüksiyonda Cookie/Token tabanlı koruma gerekir.
CREATE POLICY "Public can create sessions" ON "public"."Chat_Sessions" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can read their own session" ON "public"."Chat_Sessions" FOR SELECT USING (true); -- Basitleştirildi

CREATE POLICY "Public can insert messages" ON "public"."Chat_Messages" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can read messages" ON "public"."Chat_Messages" FOR SELECT USING (true); -- Basitleştirildi

-- Admin Policies (Authenticated users)
CREATE POLICY "Admins can do everything on sessions" ON "public"."Chat_Sessions" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can do everything on messages" ON "public"."Chat_Messages" FOR ALL USING (auth.role() = 'authenticated');
