-- Create Hotel_Information_Table
CREATE TABLE IF NOT EXISTS "public"."Hotel_Information_Table" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "name" text NOT NULL,
    "slug" text,
    "description" text,
    "image_url" text,
    "address" text
);

-- Create Rooms_Information
CREATE TABLE IF NOT EXISTS "public"."Rooms_Information" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "type_name" text NOT NULL,
    "description" text,
    "base_price" numeric,
    "capacity" integer,
    "quantity" integer DEFAULT 10
);

-- Create Reservation_Information
CREATE TABLE IF NOT EXISTS "public"."Reservation_Information" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "hotel_id" bigint REFERENCES "public"."Hotel_Information_Table"("id"),
    "room_id" bigint REFERENCES "public"."Rooms_Information"("id"),
    "customer_name" text,
    "customer_email" text,
    "check_in" date,
    "check_out" date,
    "guests_count" integer,
    "total_price" numeric,
    "room_status" text DEFAULT 'pending'
);

-- Enable RLS
ALTER TABLE "public"."Hotel_Information_Table" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Rooms_Information" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Reservation_Information" ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow public access for demo purposes - SECURE THIS IN PRODUCTION)
CREATE POLICY "Enable read access for all users" ON "public"."Hotel_Information_Table" FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON "public"."Hotel_Information_Table" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON "public"."Hotel_Information_Table" FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON "public"."Hotel_Information_Table" FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Rooms_Information" FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON "public"."Rooms_Information" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON "public"."Rooms_Information" FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON "public"."Rooms_Information" FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Reservation_Information" FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON "public"."Reservation_Information" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON "public"."Reservation_Information" FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON "public"."Reservation_Information" FOR DELETE USING (true);

