-- 1. ENUM TYPES
-- Create reservation status type if appropriate, otherwise we use text with check constraints.
-- To allow flexibility based on existing data, we will use TEXT with Check constraints or just TEXT for now,
-- but since ADD_MISSING_STATUSES.sql implied a type, let's try to define it safeley.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reservation_status') THEN
        CREATE TYPE reservation_status AS ENUM ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'completed');
    END IF;
END $$;

-- 2. TABLES

-- Hotel_Information_Table
CREATE TABLE IF NOT EXISTS "public"."Hotel_Information_Table" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "name" text NOT NULL,
    "slug" text,
    "description" text,
    "image_url" text,
    "address" text
);

-- Rooms_Information
CREATE TABLE IF NOT EXISTS "public"."Rooms_Information" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "type_name" text NOT NULL,
    "description" text,
    "base_price" numeric,
    "capacity" integer,
    "quantity" integer DEFAULT 10,
    "hotel_id" bigint REFERENCES "public"."Hotel_Information_Table"("id") ON DELETE SET NULL
);

-- Reservation_Information
CREATE TABLE IF NOT EXISTS "public"."Reservation_Information" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now(),
    "hotel_id" bigint REFERENCES "public"."Hotel_Information_Table"("id"),
    "room_id" bigint REFERENCES "public"."Rooms_Information"("id"),
    "customer_name" text,
    "customer_email" text,
    "customer_phone" text,
    "check_in" date,
    "check_out" date,
    "guests_count" integer DEFAULT 1,
    "total_price" numeric,
    "room_status" text DEFAULT 'pending', -- Using text for broader compatibility, or cast to reservation_status if strict
    "guest_id_number" text,
    "guest_nationality" text,
    "check_in_notes" text,
    "extra_charges" numeric DEFAULT 0,
    "damage_report" text,
    "payment_status" text DEFAULT 'unpaid'
);

-- 3. ROW LEVEL SECURITY (RLS)

ALTER TABLE "public"."Hotel_Information_Table" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Rooms_Information" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Reservation_Information" ENABLE ROW LEVEL SECURITY;

-- Hotel Policies
DROP POLICY IF EXISTS "Public Read Hotels" ON "public"."Hotel_Information_Table";
CREATE POLICY "Public Read Hotels" ON "public"."Hotel_Information_Table" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Hotels" ON "public"."Hotel_Information_Table";
CREATE POLICY "Admin All Hotels" ON "public"."Hotel_Information_Table" FOR ALL USING (auth.role() = 'authenticated');

-- Room Policies
DROP POLICY IF EXISTS "Public Read Rooms" ON "public"."Rooms_Information";
CREATE POLICY "Public Read Rooms" ON "public"."Rooms_Information" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Rooms" ON "public"."Rooms_Information";
CREATE POLICY "Admin All Rooms" ON "public"."Rooms_Information" FOR ALL USING (auth.role() = 'authenticated');

-- Reservation Policies
-- Public cannot see reservations directly (Privacy)
-- Public cannot create directly (must use RPC function for validation)
DROP POLICY IF EXISTS "Admin All Reservations" ON "public"."Reservation_Information";
CREATE POLICY "Admin All Reservations" ON "public"."Reservation_Information" FOR ALL USING (auth.role() = 'authenticated');

-- 4. FUNCTIONS & RPC

-- Drop old versions to ensure clean slate
DROP FUNCTION IF EXISTS "public"."create_booking_safe"(bigint, text, text, text, date, date, integer, numeric, bigint);
DROP FUNCTION IF EXISTS "public"."create_booking_safe"(bigint, text, text, text, date, date, integer, numeric);
DROP FUNCTION IF EXISTS "public"."create_booking_safe"(bigint, text, text, date, date, integer);

-- Create the latest robust version
CREATE OR REPLACE FUNCTION "public"."create_booking_safe"(
    p_room_id bigint,
    p_customer_name text,
    p_customer_email text,
    p_customer_phone text,
    p_check_in date,
    p_check_out date,
    p_guests_count integer,
    p_total_price numeric DEFAULT 0,
    p_hotel_id bigint DEFAULT NULL
)
RETURNS TABLE (success boolean, data bigint, error text) 
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with admin privileges to bypass RLS for public users
AS $$
DECLARE
    v_room_count integer;
    v_booking_count integer;
    v_new_id bigint;
    v_final_hotel_id bigint;
BEGIN
    -- 1. Determine Hotel ID if not provided
    IF p_hotel_id IS NOT NULL THEN
        v_final_hotel_id := p_hotel_id;
    ELSE
        SELECT "hotel_id" INTO v_final_hotel_id FROM "public"."Rooms_Information" WHERE id = p_room_id;
    END IF;

    -- 2. Check Room Existence
    SELECT "quantity" INTO v_room_count FROM "public"."Rooms_Information" WHERE id = p_room_id;
    
    IF v_room_count IS NULL THEN
        RETURN QUERY SELECT false, 0::bigint, 'Oda bulunamadı'::text;
        RETURN;
    END IF;

    -- 3. Check Availability (Overlapping dates check)
    SELECT COUNT(*) INTO v_booking_count 
    FROM "public"."Reservation_Information"
    WHERE room_id = p_room_id
    AND room_status NOT IN ('cancelled', 'checked_out', 'completed')
    AND (
        (check_in <= p_check_in AND check_out > p_check_in) OR
        (check_in < p_check_out AND check_out >= p_check_out) OR
        (check_in >= p_check_in AND check_out <= p_check_out)
    );

    IF v_booking_count >= v_room_count THEN
        RETURN QUERY SELECT false, 0::bigint, 'Seçilen tarihlerde boş oda yok'::text;
        RETURN;
    END IF;

    -- 4. Insert Booking
    INSERT INTO "public"."Reservation_Information" (
        hotel_id, room_id, customer_name, customer_email, customer_phone, 
        check_in, check_out, guests_count, total_price, room_status
    ) VALUES (
        v_final_hotel_id, p_room_id, p_customer_name, p_customer_email, p_customer_phone,
        p_check_in, p_check_out, p_guests_count, p_total_price, 'pending'
    ) RETURNING id INTO v_new_id;

    RETURN QUERY SELECT true, v_new_id, 'Rezervasyon başarılı'::text;
END;
$$;
